### ISSUE TITLE
ModuleNotFoundError: No module named 'osfclient'

### ISSUE THREAD

**Issue by jcohenadad** [exmakhina/distriploy#2]
Getting this error with 841c74f on this repos: https://github.com/sct-data/sct_testing_data/tree/30ffe8879d0d942e6565e503deb78044a4c354e5:
~~~
julien-macbook:~/temp/sct_testing_data $ distriploy 
2020-07-07 09:58:09 julien-macbook.JOOWIN distriploy.distriploy[5105] ERROR Error importing osf: No module named 'osfclient'
Traceback (most recent call last):
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/distriploy.py", line 55, in mirror
    mod = importlib.import_module(".mirror_{}".format(mirror_method_name), package=__package__)
  File "/Users/julien/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/mirror_osf.py", line 5, in <module>
    from .osf import *
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/osf.py", line 7, in <module>
    import osfclient
ModuleNotFoundError: No module named 'osfclient'
["https://github.com/sct-data/sct_testing_data/releases/download/r20200504-10-g2da5124/sct_testing_data-r20200504-10-g2da5124.zip"]
~~~

i guess we just need to ask users to install https://github.com/osfclient/osfclient, right?

**Comment by jcohenadad** [comment]
After installing osfclient, i get this:
~~~
julien-macbook:~/temp/sct_testing_data $ distriploy 
2020-07-07 10:03:44 julien-macbook.JOOWIN distriploy.distriploy[5452] ERROR Error running osf: 'OSF_USERNAME'
Traceback (most recent call last):
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/distriploy.py", line 61, in mirror
    mirror_meta = mod.mirror(repo_path, info, release_meta)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/mirror_osf.py", line 13, in mirror
    username = os.environ["OSF_USERNAME"]
  File "/Users/julien/miniconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'OSF_USERNAME'
["https://github.com/sct-data/sct_testing_data/releases/download/r20200504-11-g30ffe88/sct_testing_data-r20200504-11-g30ffe88.zip"]
~~~

So, that's something else to document

**Comment by jcohenadad** [comment]
The following commands are required:
~~~
export OSF_USERNAME=<USERNAME>
export OSF_PASSWORD=<PASSWORD>
~~~

**Comment by jcohenadad** [comment]
There is also the possibility to create token with OSF, that would probably be a more sustainable option?

**Comment by zougloub** [comment]
Note that the setup.py has an `"osf"` option which pulls `osflient`. But I did forget to mention that pip setup option `[osf]` should be provided to use OSF.

**Comment by zougloub** [comment]
Also forgot to document the OSF-related environment variables.

**Comment by zougloub** [comment]
Added README information.

**Comment by jcohenadad** [comment]
> Note that the setup.py has an "osf" option which pulls osflient. But I did forget to mention that pip setup option [osf] should be provided to use OSF.

reopening to add info in the doc about this

**Comment by jcohenadad** [comment]
@zougloub how can someone use the osf option mentioned above ^ with pip install?

**Comment by zougloub** [comment]
`pip install distriploy[osf]`
