### ISSUE TITLE
HTTP Error 422

### ISSUE THREAD

**Issue by charleygros** [exmakhina/distriploy#6]
Repo to deploy: https://github.com/ivadomed/data_spinegeneric_registered

I got the following error when deploying it.

```
(py36Jan) chgroc@rosenberg:~/data_spinegeneric_registered$ python -m distriploy
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/__main__.py", line 81, in <module>
    ret = main()
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/__main__.py", line 71, in main
    release_meta = release(args.repository, args.revision, config)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/distriploy.py", line 58, in release
    return mod.release(repo_path, revision, cfg_release)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/release_github.py", line 37, in release
    release_id = create_release(github_repo, git_tag, github_token, cfg_root)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/github.py", line 74, in create_release
    with urllib.request.urlopen(req) as resp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

**Comment by charleygros** [comment]
A release name is needed. My bad.
