### ISSUE TITLE
distriploy without mirror

### ISSUE THREAD

**Issue by charleygros** [exmakhina/distriploy#7]
I am trying to use distriploy for this repo': https://github.com/ivadomed/data_spinegeneric_registered

which does not have any mirror for now.

I got the following error:
```
(py36Jan) chgroc@rosenberg:~/data_spinegeneric_registered$ python -m distriploy --revision r20200907
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/__main__.py", line 81, in <module>
    ret = main()
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/__main__.py", line 73, in main
    mirror_metas = mirror(args.repository, config, release_meta)
  File "/home/GRAMES.POLYMTL.CA/chgroc/py36Jan/lib/python3.6/site-packages/distriploy/distriploy.py", line 67, in mirror
    cfg_mirrors = config["mirrors"]
KeyError: 'mirrors'
```

**Comment by jcohenadad** [comment]
@zougloub do you have any update on this? thanks
