### ISSUE TITLE
ValueError: https://github.com/sct-data/sct_testing_data

### ISSUE THREAD

**Issue by jcohenadad** [exmakhina/distriploy#8]
The command below worked in the past, not sure that has changed?
~~~
julien-macbook:~/code/sct_testing_data $ distriploy 
2020-09-03 18:03:13 julien-macbook.local distriploy.distriploy[85305] ERROR Error importing github: https://github.com/sct-data/sct_testing_data
Traceback (most recent call last):
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/distriploy.py", line 37, in release
    return mod.release(repo_path, revision, cfg_release)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/release_github.py", line 30, in release
    github_repo = get_remote(repo_path, cfg_root)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/github.py", line 45, in get_remote
    raise ValueError(url)
ValueError: https://github.com/sct-data/sct_testing_data
Traceback (most recent call last):
  File "/Users/julien/miniconda3/bin/distriploy", line 8, in <module>
    sys.exit(main())
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/__main__.py", line 71, in main
    release_meta = release(args.repository, args.revision, config)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/distriploy.py", line 37, in release
    return mod.release(repo_path, revision, cfg_release)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/release_github.py", line 30, in release
    github_repo = get_remote(repo_path, cfg_root)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/distriploy/github.py", line 45, in get_remote
    raise ValueError(url)
ValueError: https://github.com/sct-data/sct_testing_data
~~~

**Comment by jcohenadad** [comment]
Solution: git clone the repository with ssh instead of https.

This should be documented

**Comment by jcohenadad** [comment]
Documented in https://github.com/neuropoly/distriploy/commit/713f9f6018f6696fe512c9e0dd3e14e5d9e17426
